### ISSUE TITLE
Duplicate nodes are created when using multiple tables

### ISSUE THREAD

**Issue by flogy** [davidpaulsson/gatsby-source-airtable-next#6]
When using multiple tables in a base, duplicate nodes are generated (cumulatively). E.g. if table 1 has 10 rows and table 2 has 20 rows, the plugin will generate 10 nodes for table 1 and 30 for table 2. The reason behind is that the row array is not reset between table iterations.

**Comment by davidpaulsson** [comment]
published with [4.3.1](https://www.npmjs.com/package/gatsby-source-airtable-next)

**Comment by flogy** [comment]
Hey @davidpaulsson 

Thanks for the quick release. Unfortunately it seems that the JS files were not built. Does this have to be done manually when committing new changes? I only changed the TS files as I thought it will build the new JS files during the release process and thus the released hotfix is not working.

**Comment by davidpaulsson** [comment]
@flogy my bad! yes, i haven't put too much time into this process 😓 I did a build in the src directory now and pushed, so expect 4.3.2 soon!
